# Generated by Django 4.0.4 on 2022-05-13 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('desc_calibre', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObjetoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('tipo_de_objeto', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos', to='core.objetotipo')),
            ],
        ),
        migrations.CreateModel(
            name='Municao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('marca', models.CharField(max_length=64)),
                ('modelo', models.CharField(max_length=64)),
                ('valor_estimado', models.FloatField()),
                ('calibre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='munições', to='core.calibre')),
            ],
            options={
                'verbose_name': 'Munição',
                'verbose_name_plural': 'Munições',
            },
        ),
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('marca', models.CharField(max_length=64)),
                ('modelo', models.CharField(max_length=64)),
                ('quantidade_de_tiros', models.IntegerField()),
                ('valor_estimado', models.FloatField()),
                ('imagem', models.URLField(blank=True)),
                ('calibre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='armas', to='core.calibre')),
            ],
            options={
                'verbose_name': 'Arma',
                'verbose_name_plural': 'Armas',
            },
        ),
    ]
